***REMOVED***

  Twitter-connector:
***REMOVED***
***REMOVED***# Url to twitter connector
***REMOVED***Url: "https://api.twitter.com"

***REMOVED***# Key to connect to the Twitter Account
***REMOVED***Key: 

***REMOVED***# SecretKey to connect to the Twitter Account
***REMOVED***SecretKey: 
