name: Release Drafter

on:
  push:
***REMOVED***branches:
***REMOVED***  - master
***REMOVED***  - release/*
  pull_request:
***REMOVED***types: [opened, reopened, synchronize]

jobs:
  release_drafter:
***REMOVED***uses: axonivy-market/github-workflows/.github/workflows/release-drafter.yml@v5
